name: Github Release apk
on:
  push:
    tags: "v*"
jobs:
  build:
    name: Build Github release apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.5"
      - run: flutter pub get
      - run: flutter build apk --release --flavor dev
      - run: flutter build apk --release --flavor staging
      - run: flutter build apk --release --flavor prod
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Production APK to Firebase app distrubution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.0.0
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          group: testers
          file: build/app/outputs/flutter-apk/app-prod-release.apk
